name: development-automation
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
        target:
          description: 'Deployment target'
          required: true
          default: 'staging'

env:
  RESOURCE_TYPE: "app"
  ENVIRONMENT: "dev"
  INSTANCE: "01"
  LABEL: "GAS-223"
  APP_CCPVAULT: "kv-ccp-dev-weu-1"
  RG_CCPVAULT: "rg-ccp-dev-weu-1"
  VITE_MODE: develop
  VITE_SCOPE_AZURE_CMS: ${{ vars.VITE_SCOPE_AZURE_CMS }}
  

permissions:
  id-token: write
  contents: read

jobs:
  fetch-secrets:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Get Inputs
        run: |
          echo "Log level: ${{ inputs.target }}"
          echo "Ejecutando correctamente la entreda....."
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Fetch secrets from Azure Key Vault
      #   id: keyvault
      #   uses: azure/get-keyvault-secrets@v1
      #   with:
      #     keyvault: "<YOUR-KEYVAULT-NAME>"
      #     secrets: |
      #       API_KEY
      #       DATABASE_URL

      # - name: Create .env file
      #   run: |
      #     echo "VITE_API_KEY=${{ steps.keyvault.outputs.API_KEY }}"
      #     echo "DATABASE_URL=${{ steps.keyvault.outputs.DATABASE_URL }}"

      # - name: Deploy or test
      #   run: |
      #     # Optional: build, test, or deploy your SvelteKit app here
      #     cat .env
